#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Unit Tests Check
on:
  pull_request:
    branches:
      - flink-1.11
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run check and test
        run: |
          ./tools/retry.sh mvn -B -ntp clean install

  unit-tests-local:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: install Pulsar Service
        run: |
          apt update && apt install -y wget
          cd /tmp
          wget -O 'apache-pulsar-2.7.0-bin.tar.gz' 'https://archive.apache.org/dist/pulsar/pulsar-2.7.0/apache-pulsar-2.7.0-bin.tar.gz'
          tar -xvzf apache-pulsar-2.7.0-bin.tar.gz
          cd apache-pulsar-2.7.0
          chmod +x ./bin/*
          nohup ./bin/pulsar standalone --no-stream-storage -nfw &
      - name: run batch test
        run: |
          export PULSAR_ADMIN_URL=http://127.0.0.1:8080
          export PULSAR_SERVICE_URL=pulsar://127.0.0.1:6650
          export PULSAR_ZK_URL=127.0.0.1:2181
          mvn -ntp install -DskipTests
          mvn -ntp test -pl pulsar-flink-connector -Dtest=org.apache.flink.batch.connectors.pulsar.PulsarInputFormatITest
